# +docs:section=Global

# Default values for cert-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  # Set the verbosity of cert-manager. Range of 0 - 6 with 6 being the most verbose.
  logLevel: 2

# Install the cert-manager CRDs, it is recommended to not use Helm to manage
# the CRDs
installCRDs: true

# +docs:section=Controller

# Number of replicas of the cert-manager controller to run.
#
# The default is 1, but in production you should set this to 2 or 3 to provide high
# availability.
#
# If `replicas > 1` you should also consider setting `podDisruptionBudget.enabled=true`.
#
# Note: cert-manager uses leader election to ensure that there can
# only be a single instance active at a time.
replicaCount: 1

# The maximum number of challenges that can be scheduled as 'processing' at once
maxConcurrentChallenges: 60

# When this flag is enabled, secrets will be automatically removed when the certificate resource is deleted
enableCertificateOwnerRef: true

# Resources to provide to the cert-manager controller pod
#
# For example:
#  requests:
#    cpu: 10m
#    memory: 32Mi
#
# ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources:
  {}
  # requests:
  #   cpu: 10m
  #   memory: 32Mi

# A Kubernetes Affinity, if required; see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#affinity-v1-core
#
# For example:
#   affinity:
#     nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: foo.bar.com/role
#            operator: In
#            values:
#            - master
affinity: {}

# A list of Kubernetes Tolerations, if required; see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core
#
# For example:
#   tolerations:
#   - key: foo.bar.com/role
#     operator: Equal
#     value: master
#     effect: NoSchedule
tolerations: []

# +docs:section=Prometheus

prometheus:
  # Enable Prometheus monitoring for the cert-manager controller to use with the
  # Prometheus Operator. If this option is enabled without enabling `prometheus.servicemonitor.enabled` or
  # `prometheus.podmonitor.enabled`, 'prometheus.io' annotations are added to the cert-manager Deployment
  # resources. Additionally, a service is created which can be used together
  # with your own ServiceMonitor (managed outside of this Helm chart).
  # Otherwise, a ServiceMonitor/ PodMonitor is created.
  enabled: true

# +docs:section=Webhook

webhook:
  # Number of replicas of the cert-manager webhook to run.
  #
  # The default is 1, but in production you should set this to 2 or 3 to provide high
  # availability.
  #
  # If `replicas > 1` you should also consider setting `webhook.podDisruptionBudget.enabled=true`.
  replicaCount: 1

  # Resources to provide to the cert-manager webhook pod
  #
  # For example:
  #  requests:
  #    cpu: 10m
  #    memory: 32Mi
  #
  # ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources: {}

  # A Kubernetes Affinity, if required; see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#affinity-v1-core
  #
  # For example:
  #   affinity:
  #     nodeAffinity:
  #      requiredDuringSchedulingIgnoredDuringExecution:
  #        nodeSelectorTerms:
  #        - matchExpressions:
  #          - key: foo.bar.com/role
  #            operator: In
  #            values:
  #            - master
  affinity: {}

  # A list of Kubernetes Tolerations, if required; see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core
  #
  # For example:
  #   tolerations:
  #   - key: foo.bar.com/role
  #     operator: Equal
  #     value: master
  #     effect: NoSchedule
  tolerations: []

# +docs:section=CA Injector

cainjector:
  # Create the CA Injector deployment
  enabled: true

  # Number of replicas of the cert-manager cainjector to run.
  #
  # The default is 1, but in production you should set this to 2 or 3 to provide high
  # availability.
  #
  # If `replicas > 1` you should also consider setting `cainjector.podDisruptionBudget.enabled=true`.
  #
  # Note: cert-manager uses leader election to ensure that there can
  # only be a single instance active at a time.
  replicaCount: 1

  # Resources to provide to the cert-manager cainjector pod
  #
  # For example:
  #  requests:
  #    cpu: 10m
  #    memory: 32Mi
  #
  # ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources: {}

  # A Kubernetes Affinity, if required; see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#affinity-v1-core
  #
  # For example:
  #   affinity:
  #     nodeAffinity:
  #      requiredDuringSchedulingIgnoredDuringExecution:
  #        nodeSelectorTerms:
  #        - matchExpressions:
  #          - key: foo.bar.com/role
  #            operator: In
  #            values:
  #            - master
  affinity: {}

  # A list of Kubernetes Tolerations, if required; see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#toleration-v1-core
  #
  # For example:
  #   tolerations:
  #   - key: foo.bar.com/role
  #     operator: Equal
  #     value: master
  #     effect: NoSchedule
  tolerations: []

# +docs:section=Startup API Check
# This startupapicheck is a Helm post-install hook that waits for the webhook
# endpoints to become available.
# The check is implemented using a Kubernetes Job - if you are injecting mesh
# sidecar proxies into cert-manager pods, you probably want to ensure that they
# are not injected into this Job's pod. Otherwise the installation may time out
# due to the Job never being completed because the sidecar proxy does not exit.
# See https://github.com/cert-manager/cert-manager/pull/4414 for context.

startupapicheck:
  # Enables the startup api check
  enabled: true

  # Resources to provide to the cert-manager controller pod
  #
  # For example:
  #  requests:
  #    cpu: 10m
  #    memory: 32Mi
  #
  # ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  resources: {}
