---
driver:
  name: nfs.csi.k8s.io
  mountPermissions: "0777"

feature:
  enableFSGroupPolicy: true
  enableInlineVolume: false
  propagateHostMountOptions: false

controller:
  name: csi-nfs-controller
  replicas: 1
  runOnControlPlane: true
  defaultOnDeletePolicy: delete # available values: delete, retain
  resources:
    csiProvisioner:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiSnapshotter:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi
    livenessProbe:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nfs:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi

node:
  name: csi-nfs-node
  resources:
    livenessProbe:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nodeDriverRegistrar:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nfs:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi
