---
# The IPv4 cidr pool to create on startup if none exists. Pod IPs will be
# chosen from this range.
podCidr: "10.244.0.0/16"

flannel:
  # flannel command arguments
  args:
    - "--ip-masq"
    - "--kube-subnet-mgr"
    - "--iface=enp0s3"
