apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: intnet-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.16.0.50/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: extnet-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.50/32
