apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-skooner
  namespace: skooner
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: skooner.hitesh.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: skooner
            port:
              number: 80
  ingressClassName: nginx
