---
# tasks file for k8s_keycloak
- name: Execute keycloak role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Create volume directory on nfs if it does not exist
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
        owner: 1000
        group: 1000
      with_items:
        - "/home/{{ kubernetes_user }}/nfs/ssd_0/pv-keycloak-postgresql-ha-primary"

    - name: Install prereq for keycloak
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s:
          - pv/pv_keycloak_postgresql_ha_primary.j2

    - name: Install prereq for keycloak
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls:
          - files/keycloak_namespace.yml
          - files/pvc_keycloak_postgresql_ha_primary.yml

    - name: Install prereq for keycloak
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s:
          - secret/keycloak_admin_secret.j2

    - name: Add bitnami helm repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Copy values file
      ansible.builtin.copy:
        src: files/keycloak_values.yml
        dest: "{{ tmpdir }}/keycloak_values.yml"
      changed_when: false

    - name: Copy values file
      ansible.builtin.template:
        src: values/keycloak_values_var.j2
        dest: "{{ tmpdir }}/keycloak_values_var.yml"
      changed_when: false

    - name: Deploy latest version of keycloak chart
      kubernetes.core.helm:
        name: keycloak
        chart_ref: bitnami/keycloak
        chart_version: 21.0.0
        update_repo_cache: true
        release_namespace: keycloak-system
        create_namespace: true
        values_files:
          - "{{ tmpdir }}/keycloak_values.yml"
          - "{{ tmpdir }}/keycloak_values_var.yml"
        wait: true
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tmpdir }}/keycloak_values.yml"
        - "{{ tmpdir }}/keycloak_values_var.yml"
      changed_when: false

    - name: Install ingress internal
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s:
          - ingress/keycloak_ingress_internal.j2

    - name: Install grafana dashboard for keycloak
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls:
          - files/keycloak_grafana_dashboard.yml
