---
# tasks file for k8s_keycloak
- name: Execute keycloak role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Install prereq for keycloak
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/keycloak_namespace.yml
          - files/pvc_keycloak_postgresql_ha_primary.yml

    - name: Install prereq for keycloak
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - secret/keycloak_admin_secret.j2

    - name: Add bitnami helm repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Copy values file
      ansible.builtin.copy:
        src: files/keycloak_values.yml
        dest: "{{ k8s_keycloak_tmpdir }}/keycloak_values.yml"
        mode: "0777"
      changed_when: false

    - name: Copy values file
      ansible.builtin.template:
        src: values/keycloak_values_var.j2
        dest: "{{ k8s_keycloak_tmpdir }}/keycloak_values_var.yml"
        mode: preserve
      changed_when: false

    - name: Deploy latest version of keycloak chart
      kubernetes.core.helm:
        name: keycloak
        chart_ref: bitnami/keycloak
        chart_version: 24.4.9
        update_repo_cache: true
        release_namespace: keycloak-system
        create_namespace: true
        values_files:
          - "{{ k8s_keycloak_tmpdir }}/keycloak_values.yml"
          - "{{ k8s_keycloak_tmpdir }}/keycloak_values_var.yml"
        wait: true
        timeout: "15m0s"
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ k8s_keycloak_tmpdir }}/keycloak_values.yml"
        - "{{ k8s_keycloak_tmpdir }}/keycloak_values_var.yml"
      changed_when: false

    - name: Install ingress internal
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - ingress/keycloak_ingress_internal.j2

    - name: Install grafana dashboard for keycloak
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/keycloak_grafana_dashboard.yml
