---
# defaults file for k8s_init
k8s_init_coredns_entries:
  []
  # - name: gitea
  #   type: exact
  #   from: gitea.domain.com
  #   to: ingress-nginx-controller.nginx-system.svc.cluster.local
  # - name: jenkins
  #   type: exact
  #   from: jenkins.domain.com
  #   to: ingress-nginx-controller.nginx-system.svc.cluster.local
  # - name: all
  #   type: regex
  #   from: j(?:[^.]+\\.)?domain\\.com
  #   to: ingress-nginx-controller.nginx-system.svc.cluster.local

# temp directory
k8s_init_tmpdir: /tmp

k8s_init_nfs_server: "{{ nfs_server | default('nfs.domain.com') }}"

k8s_init_kubernetes_connection_interface: enp0s3
k8s_init_ingress_root_domain: "{{ kubernetes_ingress_root_domain | default('domain.com') }}"

k8s_init_metallb_ip_address_pool: intnet-pool
k8s_init_metallb_ip_address_range: 172.16.0.50/32

# cert manager ca
k8s_init_cert_manager_ca_crt: ""
k8s_init_cert_manager_ca_key: ""
