apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-keycloak-postgresql-primary
  namespace: keycloak-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv-keycloak-postgresql-ha-primary
