---
- name: Apt update, upgrade, reboot
  become: true
  become_user: root
  block:
    - name: Upgrade all APT packages
      ansible.builtin.apt:
        upgrade: "yes"
        update_cache: true
      notify:
        - Reboot Machine

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove useless packages from the system
      ansible.builtin.apt:
        autoremove: true
