---
- name: Apt remove, cleanup
  become: true
  become_user: root
  block:
    - name: Remove APT Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      with_items: "{{ apt_remove }}"

    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true

    - name: Remove useless packages from the system
      ansible.builtin.apt:
        autoremove: true
