- name: Install Node Exporter
  become: true
  become_user: root
  block:
    - name: Install wget
      include_tasks: apt_install.yml
      vars:
        apt_install:
          - wget

    - name: Download latest node exporter
      command: wget https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
    
    - name: Extract node exporter archieve
      command: tar xvfz node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
 
    - name: Move node-exporter to /usr/sbin
      command: mv node_exporter-{{node_exporter_version}}.linux-amd64/node_exporter /usr/sbin
 
    - name: Cleanup extracted files
      ansible.builtin.file:
        state: absent
        path: node_exporter-{{node_exporter_version}}.linux-amd64

    - name: Cleanup extracted files
      ansible.builtin.file:
        state: absent
        path: node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz

    - name: Create user node_exporter
      user:
        name: node_exporter
        system: yes
        create_home: no
        shell: /sbin/nologin

    - name: Create text file collector directory
      ansible.builtin.file:
        state: directory
        path: /var/lib/node_exporter/textfile_collector
        owner: node_exporter
        group: node_exporter

    - name: Create sysconfig directory
      ansible.builtin.file:
        state: directory
        path: /etc/sysconfig

    - name: Create node_exporter sysconfig
      copy:
        src: files/etc/sysconfig/node_exporter
        dest: /etc/sysconfig/node_exporter
        mode: '0644'

    - name: Create node_exporter.socket
      copy:
        src: files/etc/systemd/system/node_exporter.socket
        dest: /etc/systemd/system/node_exporter.socket
        mode: '0644'

    - name: Create node_exporter.service
      copy:
        src: files/etc/systemd/system/node_exporter.service
        dest: /etc/systemd/system/node_exporter.service
        mode: '0644'

    - name: Restart and enable node exporter service
      ansible.builtin.service:
        name: node_exporter
        daemon_reload: yes
        state: restarted
        enabled: true
