---
- name: Install k8s yml manifests
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Install local yml files
      block:
        - name: Copy YML files to remote
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "{{ tmpdir }}/{{ item | basename }}"
          with_items: "{{ k8s_install_ymls }}"
          changed_when: false

        - name: Apply YML files to k8s
          kubernetes.core.k8s:
            state: present
            src: "{{ tmpdir }}/{{ item | basename }}"
            wait: true
          with_items: "{{ k8s_install_ymls }}"
          when: not ansible_check_mode

        - name: Remove temp files (delete file)
          ansible.builtin.file:
            path: "{{ tmpdir }}/{{ item | basename }}"
            state: absent
          with_items: "{{ k8s_install_ymls }}"
          changed_when: false

    - name: Install remote yml files
      block:
        - name: Download remote yml files
          ansible.builtin.get_url:
            url: "{{ item }}"
            dest: "{{ tmpdir }}/{{ item | basename }}"
            mode: "0664"
          with_items: "{{ k8s_install_urls }}"
          changed_when: false

        - name: Apply remote yml files
          kubernetes.core.k8s:
            state: present
            src: "{{ tmpdir }}/{{ item | basename }}"
            wait: true
          with_items: "{{ k8s_install_urls }}"
          when: not ansible_check_mode

        - name: Remove temp files (delete file)
          ansible.builtin.file:
            path: "{{ tmpdir }}/{{ item | basename }}"
            state: absent
          with_items: "{{ k8s_install_urls }}"
          changed_when: false
