- name: Install k8s j2 template manifests
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Install j2 manifest files
      block:
        - name: Create yml from template in temp location
          ansible.builtin.template:
            src: "{{ item }}"
            dest: "{{ tmpdir }}/{{ item | basename | split('.') | first }}.yml"
          with_items: "{{ k8s_install_j2s }}"
          changed_when: false

        - name: Apply YML files to k8s
          kubernetes.core.k8s:
            state: present
            src: "{{ tmpdir }}/{{ item | basename | split('.') | first }}.yml"
            wait: true
          with_items: "{{ k8s_install_j2s }}"
          when: not ansible_check_mode
        
        - name: Remove temp files (delete file)
          ansible.builtin.file:
            path: "{{ tmpdir }}/{{ item | basename | split('.') | first }}.yml"
            state: absent
          with_items: "{{ k8s_install_j2s }}"
          changed_when: false
