---
- name: Pip install modules
  become: true
  become_user: root
  block:
    - name: Install Python pip3
      ansible.builtin.include_tasks: apt_install.yml
      vars:
        utility_apt_install:
          - python3-pip

    - name: Install pip modules
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
        umask: "0022"
      with_items: "{{ utility_pip_install }}"
