---
- name: Configure Firewall
  become: true
  become_user: root
  block:
    - name: Install or Check UFW
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Disable UFW
      community.general.ufw:
        state: disabled

    - name: Reset All Rules
      community.general.ufw:
        state: reset

    - name: Set UFW default forward policy to ACCEPT
      ansible.builtin.lineinfile:
        dest: /etc/default/ufw
        line: DEFAULT_FORWARD_POLICY="ACCEPT"
        regexp: "^DEFAULT_FORWARD_POLICY\\="

    - name: Allow incoming accesses
      community.general.ufw:
        rule: allow
        direction: in
        interface: "{{ ufw_interface | default('') }}"
        route: "{{ item.route | default(false) }}"
        proto: "{{ item.proto | default('any') }}"
        src: "{{ item.src | default('any') }}"
        port: "{{ item.port }}"
      loop: "{{ ufw_rules }}"

    # - name: Allow incomming on cni0
    #   community.general.ufw:
    #     rule: allow
    #     direction: in
    #     interface: cni0

    # - name: Allow incomming on flannel.1
    #   community.general.ufw:
    #     rule: allow
    #     direction: in
    #     interface: "flannel.1"

    - name: Allow SSH access from local
      community.general.ufw:
        name: OpenSSH
        rule: allow
        interface: "{{ ufw_interface | default('') }}"
        direction: in

    # - name: Reject all incomming and enable UFW
    #   community.general.ufw:
    #     state: enabled
    #     default: reject
    #     direction: incoming

    # - name: Allow all outgoing and enable UFW
    #   community.general.ufw:
    #     state: enabled
    #     default: allow
    #     direction: outgoing

    - name: Set logging
      community.general.ufw:
        logging: "on"
