---
- name: Configure netplan static ip
  become: true
  become_user: root
  block:
    - name: Install custom netplan config file
      ansible.builtin.template:
        src: etc/netplan/00-installer-config.j2
        dest: /etc/netplan/00-installer-config.yaml
        owner: root
        group: root
        mode: "0600"
      register: utility_changed_netplan
      notify:
        - Apply Netplan Config
        - Reboot Machine
