- name: Install custom hosts file
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: "{{ hosts_file_path }}"
    owner: root
    group: root
    mode: 0644
  register: installed_hosts

- name: Reboot Machine
  include_tasks: reboot.yml
  when: installed_hosts is changed