---
- name: Install custom hosts file
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/hosts.j2
    dest: "{{ utility_hosts_file_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reboot Machine
