---
- name: Install ssh banner
  become: true
  become_user: root
  block:
    - name: Add banner info in sshd.conf
      ansible.builtin.lineinfile:
        dest: "{{ utility_sshd_config_path }}"
        regexp: "#Banner /etc/issue.net"
        line: "Banner /etc/issue.net"
      register: utility_config

    - name: Update ssh banner
      ansible.builtin.template:
        src: etc/ssh_banner.j2
        dest: /etc/issue.net
        mode: "0644"
      register: utility_template

- name: Restart SSH Service
  ansible.builtin.include_tasks: systemctl_restart.yml
  vars:
    utility_systemctl_restart:
      - ssh
  when: utility_config is changed or utility_template is changed
