---
- name: Install CA Certificates
  become: true
  become_user: root
  block:
    - name: Create directory if it does not exist
      ansible.builtin.file:
        path: "{{ utility_usr_ca_cert_path }}"
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Copy CA Certificates
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ utility_usr_ca_cert_path }}/{{ item | basename }}"
        mode: "0644"
      with_items: "{{ utility_ca_certificates }}"
      notify:
        - Update CA Certificates
