---
# tasks file for k8s_harbor
- name: Execute harbor role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Create volume directory on nfs if it does not exist
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0777"
        owner: 1000
        group: 1000
      with_items:
        - "/home/{{ kubernetes_user }}/nfs/ssd_0/pv-harbor-database"
        - "/home/{{ kubernetes_user }}/nfs/ssd_0/pv-harbor-registry"

    - name: Install prereq for harbor
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s:
          - pv/pv_harbor_database.j2
          - pv/pv_harbor_registry.j2

    - name: Install prereq for harbor
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls:
          - files/harbor_namespace.yml
          - files/pvc_harbor_database.yml
          - files/pvc_harbor_registry.yml

    - name: Install prereq for harbor
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s:
          - secret/harbor_admin_secret.j2
          - secret/harbor_registry_secret.j2

    - name: Add harbor helm repository
      kubernetes.core.helm_repository:
        name: harbor
        repo_url: https://helm.goharbor.io

    - name: Copy values file
      ansible.builtin.copy:
        src: files/harbor_values.yml
        dest: "{{ tmpdir }}/harbor_values.yml"
      changed_when: false

    - name: Copy values file
      ansible.builtin.template:
        src: values/harbor_values_var.j2
        dest: "{{ tmpdir }}/harbor_values_var.yml"
      changed_when: false

    - name: Deploy latest version of harbor chart
      kubernetes.core.helm:
        name: harbor
        chart_ref: harbor/harbor
        chart_version: 1.14.1
        update_repo_cache: true
        release_namespace: harbor-system
        create_namespace: false
        values_files:
          - "{{ tmpdir }}/harbor_values.yml"
          - "{{ tmpdir }}/harbor_values_var.yml"
        wait: true
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tmpdir }}/harbor_values.yml"
        - "{{ tmpdir }}/harbor_values_var.yml"
      changed_when: false

    - name: Install grafana dashboard for harbor
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls:
          - files/harbor_grafana_dashboard.yml
