replicas: 1

## Number of old ReplicaSets to retain
##
revisionHistoryLimit: 1

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName: "default-scheduler"

image:
  # -- The Docker registry
  registry: docker.io
  # -- Docker image repository
  repository: hiteshnayak305/grafana
  # Overrides the Grafana image tag whose default is the chart appVersion
  # tag: ""

testFramework:
  enabled: false

# Enable creating the grafana configmap
createConfigmap: true

ingress:
  enabled: true
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  ingressClassName: nginx
  # Values can be templated
  #annotations: -> template
  path: /

  # pathType is only for k8s >= 1.1=
  pathType: Prefix

  # hosts: -> template

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  ## Name of an existing PVC. Can be templated.
  existingClaim: pvc-grafana

initChownData:
  ## If false, data ownership will not be reset at startup
  ## This allows the grafana-server to be run with an arbitrary user
  ##
  enabled: true

# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "grafana-admin-secret"
  userKey: admin-user
  passwordKey: admin-password

## Grafana's primary configuration
## NOTE: values in map will be converted to ini format
## ref: http://docs.grafana.org/installation/configuration/
##
grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"

#######################   issue with multiple values file  ##############

## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: https://prometheus.hitesh.com
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: https://loki.hitesh.com
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000

## Configure grafana dashboard providers
## ref: http://docs.grafana.org/administration/provisioning/#dashboards
##
## `path` must be /var/lib/grafana/dashboards/<provider_name>
##
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: true
        editable: false
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards/default

## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
##
dashboards:
  default:
    # Physical Machines
    node-exporter-full:
      gnetId: 1860
      revision: 36
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    ###### Kubernetes #############
    # Kubernetes monitorings
    kubernetes-views-global:
      gnetId: 15757
      revision: 37
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-views-namespaces:
      gnetId: 15758
      revision: 34
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-views-nodes:
      gnetId: 15759
      revision: 29
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-views-pods:
      gnetId: 15760
      revision: 26
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-system-coredns:
      gnetId: 15762
      revision: 17
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    logs-app:
      gnetId: 13639
      revision: 2
      datasource:
        - name: DS_LOKI
          value: Loki
    kubernetes-event-exporter:
      gnetId: 17882
      revision: 2
      datasource:
        - name: DS_LOKI
          value: Loki
    # Kubernetes > Ingress > Ingress Controller
    nginx-ingress-controller:
      gnetId: 9614
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

    ##### Applications ##########
    # Applications > Gitea
    gitea:
      gnetId: 13192
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    # Applications > Jenkins
    jenkins-performance-and-health-overview:
      gnetId: 9964
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    # Applications > Spring Boot
    spring-boot-observability:
      gnetId: 17175
      revision: 2
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
        - name: DS_LOKI
          value: Loki
    # Applications > Node JS
    node-js-application-dashboard:
      gnetId: 11159
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

    #### Databases ##############
    # Database > Postgresql
    postgresql-database:
      gnetId: 9628
      revision: 7
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    # Database > MongoDB
    mongodb-database:
      gnetId: 2583
      revision: 2
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

    #### Messaging ############
    # Messaging > RabbitMQ
    rabbitmq-overview:
      gnetId: 10991
      revision: 14
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

## Reference to external ConfigMap per provider. Use provider name as key and ConfigMap name as value.
## A provider dashboards must be defined either by external ConfigMaps or in values.yaml, not in both.
## ConfigMap data example:
##
## data:
##   example-dashboard.json: |
##     RAW_JSON
##
dashboardsConfigMaps: {}
#  default: ""
