serviceAccount:
  create: true
  automountServiceAccountToken: true

replicas: 1

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

## Use an alternate scheduler, e.g. "stork".
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
# schedulerName: "default-scheduler"

image:
  # -- The Docker registry
  registry: docker.io
  # -- Docker image repository
  repository: hiteshnayak305/grafana
  # Overrides the Grafana image tag whose default is the chart appVersion
  # tag: ""

testFramework:
  enabled: false

# Enable creating the grafana configmap
createConfigmap: true

## Expose the grafana service to be accessed from outside the cluster (LoadBalancer service).
## or access it from within the cluster (ClusterIP service). Set the service type and the port to serve it.
## ref: http://kubernetes.io/docs/user-guide/services/
##
service:
  enabled: true
  portName: http-web

serviceMonitor:
  ## If true, a ServiceMonitor CRD is created for a prometheus operator
  ## https://github.com/coreos/prometheus-operator
  ##
  enabled: true

ingress:
  enabled: true
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  ingressClassName: nginx
  # Values can be templated
  #annotations: -> template
  path: /

  # pathType is only for k8s >= 1.1=
  pathType: Prefix

  # hosts: -> template

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  ## Name of an existing PVC. Can be templated.
  existingClaim: pvc-grafana

initChownData:
  ## If false, data ownership will not be reset at startup
  ## This allows the grafana-server to be run with an arbitrary user
  ##
  enabled: true

# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "grafana-admin-secret"
  userKey: admin-user
  passwordKey: admin-password

## Grafana's primary configuration
## NOTE: values in map will be converted to ini format
## ref: http://docs.grafana.org/installation/configuration/
##
grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"

## Sidecars that collect the configmaps with specified label and stores the included files them into the respective folders
## Requires at least Grafana 5 to work and can't be used together with parameters dashboardProviders, datasources and dashboards
sidecar:
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 128Mi
  # skipTlsVerify Set to true to skip tls verification for kube api calls
  # skipTlsVerify: true
  enableUniqueFilenames: false
  alerts:
    enabled: false
  dashboards:
    enabled: true
    # label that the configmaps with dashboards are marked with
    label: grafana_dashboard
    # value of label that the configmaps with dashboards are set to
    labelValue: "1"
    # Namespaces list. If specified, the sidecar will search for config-maps/secrets inside these namespaces.
    # Otherwise the namespace in which the sidecar is running will be used.
    # It's also possible to specify ALL to search in all namespaces.
    searchNamespace: ALL
    # If specified, the sidecar will look for annotation with this name to create folder and put graph here.
    # You can use this parameter together with `provider.foldersFromFilesStructure`to annotate configmaps and create folder structure.
    folderAnnotation: folder
    # provider configuration that lets grafana manage the dashboards
    provider:
      # disableDelete to activate a import-only behaviour
      disableDelete: false
      # allow updating provisioned dashboards from the UI
      allowUiUpdates: false
  datasources:
    enabled: true
    # label that the configmaps with datasources are marked with
    label: grafana_datasource
    # value of label that the configmaps with datasources are set to
    labelValue: "1"
    # Log level. Can be one of: DEBUG, INFO, WARN, ERROR, CRITICAL.
    # logLevel: INFO
    # If specified, the sidecar will search for datasource config-maps inside this namespace.
    # Otherwise the namespace in which the sidecar is running will be used.
    # It's also possible to specify ALL to search in all namespaces
    searchNamespace: ALL
  plugins:
    enabled: false
  notifiers:
    enabled: false

#######################   issue with multiple values file  ##############

## Configure grafana dashboard providers
## ref: http://docs.grafana.org/administration/provisioning/#dashboards
##
## `path` must be /var/lib/grafana/dashboards/<provider_name>
##
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: true
        editable: false
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards/default

## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
##
dashboards:
  default:
    # Physical Machines
    node-exporter-full:
      gnetId: 1860
      revision: 36
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    ###### Kubernetes #############
    # Kubernetes monitorings
    kubernetes-views-global:
      gnetId: 15757
      revision: 37
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-views-namespaces:
      gnetId: 15758
      revision: 34
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-views-nodes:
      gnetId: 15759
      revision: 29
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-views-pods:
      gnetId: 15760
      revision: 26
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-system-coredns:
      gnetId: 15762
      revision: 17
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    logs-app:
      gnetId: 13639
      revision: 2
      datasource:
        - name: DS_LOKI
          value: Loki
    kubernetes-event-exporter:
      gnetId: 17882
      revision: 2
      datasource:
        - name: DS_LOKI
          value: Loki
    # Kubernetes > Cert Manager
    cert-manager:
      gnetId: 20340
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    # Kubernetes > Ingress > Ingress Controller
    nginx-ingress-controller:
      gnetId: 9614
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

    ##### Applications ##########
    # Applications > Jenkins
    jenkins-performance-and-health-overview:
      gnetId: 9964
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    # Applications > Spring Boot
    spring-boot-observability:
      gnetId: 17175
      revision: 2
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
        - name: DS_LOKI
          value: Loki
    # Applications > Node JS
    node-js-application-dashboard:
      gnetId: 11159
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

    #### Databases ##############
    # Database > Postgresql
    postgresql-database:
      gnetId: 9628
      revision: 7
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    # Database > MongoDB
    mongodb-database:
      gnetId: 2583
      revision: 2
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    # Database > Redis
    redis-dashboard-for-prometheus-redis-exporter:
      gnetId: 11835
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

    #### Messaging ############
    # Messaging > RabbitMQ
    rabbitmq-overview:
      gnetId: 10991
      revision: 14
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

## Reference to external ConfigMap per provider. Use provider name as key and ConfigMap name as value.
## A provider dashboards must be defined either by external ConfigMaps or in values.yaml, not in both.
## ConfigMap data example:
##
## data:
##   example-dashboard.json: |
##     RAW_JSON
##
dashboardsConfigMaps: {}
#  default: ""

## Number of old ReplicaSets to retain
##
revisionHistoryLimit: 1
