replicas: 1

## Number of old ReplicaSets to retain
##
revisionHistoryLimit: 1

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

testFramework:
  enabled: false

# Enable creating the grafana configmap
createConfigmap: true

ingress:
  enabled: true
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  ingressClassName: nginx
  # Values can be templated
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  path: /

  # pathType is only for k8s >= 1.1=
  pathType: Prefix

  # hosts: -> template

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 500Mi

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  ## Name of an existing PVC. Can be templated.
  existingClaim: pvc-grafana

initChownData:
  ## If false, data ownership will not be reset at startup
  ## This allows the grafana-server to be run with an arbitrary user
  ##
  enabled: true

# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "grafana-admin-secret"
  userKey: admin-user
  passwordKey: admin-password

## Configure grafana datasources
## ref: http://docs.grafana.org/administration/provisioning/#datasources
##
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.grafana-prometheus-system.svc
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki-gateway.grafana-loki-system.svc
        access: proxy
        isDefault: false
        jsonData:
          maxLines: 1000

## Configure grafana dashboard providers
## ref: http://docs.grafana.org/administration/provisioning/#dashboards
##
## `path` must be /var/lib/grafana/dashboards/<provider_name>
##
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: true
        editable: false
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dashboards/default

## Configure grafana dashboard to import
## NOTE: To use dashboards you must also enable/configure dashboardProviders
## ref: https://grafana.com/dashboards
##
## dashboards per provider, use provider name as key.
##
dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 33
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kube-state-metrics-v2:
      gnetId: 13332
      revision: 12
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
        - name: VAR_DATASOURCE
          value: Prometheus
    kubernetes-views-global:
      gnetId: 15757
      revision: 31
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    loki-stack-monitoring:
      gnetId: 14055
      revision: 5
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
        - name: DS_LOKI
          value: Loki
    logs-app:
      gnetId: 13639
      revision: 2
      datasource:
        - name: DS_LOKI
          value: Loki
    gitea:
      gnetId: 13192
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    jenkins-performance-and-health-overview:
      gnetId: 9964
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    kubernetes-event-exporter:
      gnetId: 17882
      revision: 2
      datasource:
        - name: DS_LOKI
          value: Loki
    nginx-ingress-controller:
      gnetId: 9614
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    spring-boot-observability:
      gnetId: 17175
      revision: 2
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
        - name: DS_LOKI
          value: Loki
    node-js-application-dashboard:
      gnetId: 11159
      revision: 1
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    postgresql-database:
      gnetId: 9628
      revision: 7
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus
    mongodb-database:
      gnetId: 2583
      revision: 2
      datasource:
        - name: DS_PROMETHEUS
          value: Prometheus

## Reference to external ConfigMap per provider. Use provider name as key and ConfigMap name as value.
## A provider dashboards must be defined either by external ConfigMaps or in values.yaml, not in both.
## ConfigMap data example:
##
## data:
##   example-dashboard.json: |
##     RAW_JSON
##
dashboardsConfigMaps: {}
#  default: ""

## Grafana's primary configuration
## NOTE: values in map will be converted to ini format
## ref: http://docs.grafana.org/installation/configuration/
##
grafana.ini:
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"
