---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-harbor-database
  namespace: harbor-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv-harbor-database
