apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-harbor-registry
  namespace: harbor-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pv-harbor-registry
