apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitea-postgresql-primary
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.hitesh.com
    path: "/mnt/nfs/ssd_0/pv-gitea-postgresql-primary"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitea-postgresql-primary
  namespace: gitea-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ''
  volumeName: pv-gitea-postgresql-primary