---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitea
  namespace: gitea-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pv-gitea
