---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitea-postgresql-ha-primary
  namespace: gitea-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-ssd-0-retain-retain
