---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gitea
  namespace: gitea-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: nfs-ssd-0-retain-retain
