---
# tasks file for k8s_jenkins
- name: Execute jenkins role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Install prereq for jenkins
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/jenkins_namespace.yml
          - files/pvc_jenkins_controller.yml
          - files/pvc_jenkins_maven.yml
          - files/pvc_jenkins_gradle.yml
          - files/pvc_jenkins_npm.yml
          - files/pvc_jenkins_workspace.yml
          - files/pvc_jenkins_sonar_cache.yml
          - files/pvc_jenkins_sonar_cache_maven.yml

    - name: Install prereq for jenkins
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - secret/jenkins_admin_secret.j2
          - secret/git_gitea_secret.j2
          - secret/docker_harbor_secret.j2
          - secret/helm_harbor_secret.j2
          - secret/kubectl_default_secret.j2
          - secret/sonarqube_sonarqube_secret.j2
          - secret/mail_gmail_selfhost_secret.j2
          - secret/nvd_api_secret.j2

    - name: Add Jenkins helm repository
      kubernetes.core.helm_repository:
        name: jenkins
        repo_url: https://charts.jenkins.io

    - name: Copy values files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ k8s_jenkins_tmpdir }}/{{ item | basename }}"
        mode: "0777"
      changed_when: false
      with_items:
        - files/jenkins_values.yml
        - files/jenkins_values_jcas_jenkins.yml
        - files/jenkins_values_jcas_credentials.yml
        - files/jenkins_values_jcas_unclassified.yml
        - files/jenkins_values_agent.yml
        - files/jenkins_values_jcas_security.yml
        - files/jenkins_values_jcas_appearance.yml

    - name: Copy values file
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ k8s_jenkins_tmpdir }}/{{ item | basename | splitext | first }}.yml"
        mode: preserve
      changed_when: false
      with_items:
        - values/jenkins_values_var.j2
        - values/jenkins_values_jcas_jobs_var.j2
        - values/jenkins_values_jcas_unclassified_var.j2
        - values/jenkins_values_jcas_jenkins_var.j2

    - name: Deploy latest version of jenkins chart
      kubernetes.core.helm:
        name: jenkins
        chart_ref: jenkins/jenkins
        chart_version: 5.7.21
        update_repo_cache: true
        release_namespace: jenkins
        create_namespace: false
        values_files:
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_jenkins.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_credentials.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_unclassified.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_agent.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_security.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_appearance.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_var.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_jobs_var.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_unclassified_var.yml"
          - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_jenkins_var.yml"
        wait: true
        timeout: "25m0s"
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_jenkins.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_credentials.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_unclassified.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_agent.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_security.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_appearance.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_var.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_jobs_var.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_unclassified_var.yml"
        - "{{ k8s_jenkins_tmpdir }}/jenkins_values_jcas_jenkins_var.yml"
      changed_when: false

    - name: Install ingress internal
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - ingress/jenkins_ingress_internal.j2

    - name: Install grafana dashboard
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/jenkins_performance_and_health_overview_dashboard.yml
