---
# tasks file for k8s_jenkins
- name: Execute jenkins role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Create volume directory on nfs if it does not exist
      become: true
      become_user: "root"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
        owner: 1000
        group: 1000
      with_items: 
        - "/home/{{ kubernetes_user }}/nfs/ssd_0/pv-jenkins-controller"
        - "/home/{{ kubernetes_user }}/nfs/hdd_0/pv-jenkins-maven"

    # install prereqs
    - name: Install prereq for gitea
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls: 
          - files/jenkins_namespace.yml
          - files/pvc_jenkins.yml
          - files/pvc_jenkins_maven.yml
          - files/jenkins_ingress.yml

    - name: Install prereq for jenkins 2
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s: 
          - secret/jenkins_admin_secret.j2
          - secret/jenkins_custom_root_ca_cert.j2
          - secret/gitea_credentials_secret.j2
          - secret/kube_credentials_secret.j2

    - name: Add Jenkins helm repository
      kubernetes.core.helm_repository:
        name: jenkins
        repo_url: https://charts.jenkins.io

    - name: Copy values files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ tmpdir }}/{{ item | basename }}"
      changed_when: false
      with_items: 
        - files/jenkins_values.yml
        - files/jenkins_values_jcas_credentials.yml
        - files/jenkins_values_jcas_plugins_config.yml
        - files/jenkins_values_jcas_jobs.yml
        - files/jenkins_values_agent.yml
        - files/jenkins_values_jcas_security_config.yml

    - name: Deploy latest version of jenkins chart
      kubernetes.core.helm:
        name: jenkins
        chart_ref: jenkins/jenkins
        chart_version: 4.7.2
        update_repo_cache: true
        release_namespace: jenkins
        create_namespace: false
        values_files:
          - "{{ tmpdir }}/jenkins_values.yml"
          - "{{ tmpdir }}/jenkins_values_jcas_credentials.yml"
          - "{{ tmpdir }}/jenkins_values_jcas_plugins_config.yml"
          - "{{ tmpdir }}/jenkins_values_jcas_jobs.yml"
          - "{{ tmpdir }}/jenkins_values_agent.yml"
          - "{{ tmpdir }}/jenkins_values_jcas_security_config.yml"
        wait: true
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ tmpdir }}/jenkins_values.yml"
        - "{{ tmpdir }}/jenkins_values_jcas_credentials.yml"
        - "{{ tmpdir }}/jenkins_values_jcas_plugins_config.yml"
        - "{{ tmpdir }}/jenkins_values_jcas_jobs.yml"
        - "{{ tmpdir }}/jenkins_values_agent.yml"
        - "{{ tmpdir }}/jenkins_values_jcas_security_config.yml"
      changed_when: false
