---
# defaults file for k8s_gitea

k8s_gitea_ingress_root_domain: "{{ kubernetes_ingress_root_domain | default('domain.com') }}"

# admin user
k8s_gitea_admin_username: admin
k8s_gitea_admin_password: password

# system gpg key
k8s_gitea_gpg_key: ""

# oauth secret
k8s_gitea_oauth_key: key
k8s_gitea_oauth_secret: secret
