- name: Add an apt signing key for Tailscale
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    dest: /etc/apt/keyrings/tailscale.gpg
    mode: '0644'
    force: true

- name: Adding apt repository for Tailscale
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main
    state: present
    filename: tailscale

- name: Install Tailscale binaries
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - tailscale

# - name: Install tailscale with shell
#   ansible.builtin.command: "curl -fsSL https://tailscale.com/install.sh | sh"

#- name: Tailscale login
#  ansible.builtin.command: tailscale login

- name: Tailscale up
  ansible.builtin.command: "tailscale up --authkey {{ tailscale_authkey }}"
  when: "tailscale_authkey and tailscale_authkey|length > 0"
  notify: 
    - restart tailscale
