## volumes permissions :
# 4 -r; 2 - w; x 1
#
# Octal   Decimal   String
# 0777    511       ?rwxrwxrwx
# 0700    448       ?rwx------
# 0644    420       ?rw-r--r--
# 0400    256       ?r--------

agent:
  enabled: true
  image:
    repository: "jenkins/inbound-agent"
    tag: "latest-alpine"
  workingDir: "/home/jenkins/agent"
  nodeUsageMode: "NORMAL"
  customJenkinsLabels: []
  componentName: "jenkins-agent"
  websocket: false
  directConnection: false
  privileged: true
  runAsUser: 0
  hostNetworking: false
  resources:
    requests:
      cpu: "500m"
      memory: "256Mi"
    limits:
      cpu: "1"
      memory: "500Mi"
  # You may want to change this to true while testing a new image
  alwaysPullImage: false
  # Controls how agent pods are retained after the Jenkins build completes
  # Possible values: Always, Never, OnFailure
  podRetention: "OnFailure"
  # Disable if you do not want the Yaml the agent pod template to show up
  # in the job Console Output. This can be helpful for either security reasons
  # or simply to clean up the output to make it easier to read.
  showRawYaml: false
  # You can define the volumes that you want to mount for this container
  # Allowed types are: ConfigMap, EmptyDir, HostPath, Nfs, PVC, Secret
  # Configure the attributes as they appear in the corresponding Java class for that type
  # https://github.com/jenkinsci/kubernetes-plugin/tree/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes
  volumes:
    - type: Secret
      secretName: jenkins-custom-root-ca-cert
      mountPath: /mnt/ca-certificates/custom
    - type: PVC
      claimName: pvc-jenkins-maven
      mountPath: /root/.m2
      readOnly: false
    - type: PVC
      claimName: pvc-jenkins-gradle
      mountPath: /root/.gradle
      readOnly: false
    - type: PVC
      claimName: pvc-jenkins-npm
      mountPath: /root/.npm
      readOnly: false
    - type: PVC
      claimName: pvc-jenkins-sonar-cache
      mountPath: /opt/sonar-scanner/.sonar/cache
      readOnly: false

  # You can define the workspaceVolume that you want to mount for this container
  # Allowed types are: DynamicPVC, EmptyDir, HostPath, Nfs, PVC
  # Configure the attributes as they appear in the corresponding Java class for that type
  # https://github.com/jenkinsci/kubernetes-plugin/tree/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/workspace
  workspaceVolume:
    type: PVC
    claimName: pvc-jenkins-workspace
    readOnly: false
  #   type: DynamicPVC
  #   storageClassName: nfs-client-hdd-0
  #   requestsSize: 1Gi
  #
  # Pod-wide environment, these vars are visible to any container in the agent pod
  envVars: []
  # - name: PATH
  #   value: /usr/local/bin
  # Mount a secret as environment variable
  secretEnvVars: []
  # - key: PATH
  #   optional: false # default: false
  #   secretKey: MY-K8S-PATH
  #   secretName: my-k8s-secret
  nodeSelector: {}
  # Key Value selectors. Ex:
  # jenkins-agent: v1

  # Executed command when side container gets started
  # command:
  # args: "${computer.jnlpmac} ${computer.name}"
  # Side container name
  sideContainerName: jnlp
  # Doesn't allocate pseudo TTY by default
  TTYEnabled: true
  # Max number of spawned agent
  containerCap: 2
  # Pod name
  podName: default
  # Allows the Pod to remain active for reuse until the configured number of
  # minutes has passed since the last step was executed on it.
  idleMinutes: 0
  # Defines how the raw yaml field gets merged with yaml definitions from inherited pod templates: merge or override
  yamlMergeStrategy: merge
  yamlTemplate: |-
    apiVersion: v1
    kind: Pod
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: jnlp
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt &&
                    update-ca-certificates"
  # Timeout in seconds for an agent to be online
  connectTimeout: 120
  # Annotations to apply to the pod.
  annotations: {}

  # Below is the implementation of custom pod templates for the default configured kubernetes cloud.
  # Add a key under podTemplates for each pod template. Each key (prior to | character) is just a label, and can be any value.
  # Keys are only used to give the pod template a meaningful name.  The only restriction is they may only contain RFC 1123 \ DNS label
  # characters: lowercase letters, numbers, and hyphens. Each pod template can contain multiple containers.
  # For this pod templates configuration to be loaded the following values must be set:
  # controller.JCasC.defaultConfig: true
  # Best reference is https://<jenkins_url>/configuration-as-code/reference#Cloud-kubernetes. The example below creates a python pod template.
  podTemplates:
    kaniko: |
      - name: kaniko
        label: jenkins-kaniko
        serviceAccount: jenkins
        showRawYaml: false
        inheritFrom: default
        containers:
          - name: kaniko
            image: gcr.io/kaniko-project/executor:debug
            command: "/busybox/sh -c"
            args: "cat"
            alwaysPullImage: false
            runAsUser: 0
            ttyEnabled: true
            resourceRequestCpu: "1"
            resourceRequestMemory: "500Mi"
            resourceLimitCpu: "2"
            resourceLimitMemory: "1Gi"
        volumes:
          - secretVolume:
              mountPath: /kaniko/.docker/
              secretName: gitea-docker-credentials-secret
              defaultMode: 256
          - hostPathVolume:
              mountPath: /kaniko/ssl/certs/
              hostPath: /etc/ssl/certs/
              readOnly: true
        yamlMergeStrategy: merge
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            securityContext:
              runAsUser: 0
            containers:
              - name: jnlp
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
              - name: kaniko
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "mkdir -p /usr/local/share/ca-certificates && 
                          ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt"
    k8s: |
      - name: k8s
        label: jenkins-k8s
        serviceAccount: jenkins
        showRawYaml: false
        inheritFrom: default
        containers:
          - name: k8s
            image: alpine/k8s:1.29.2
            command: "/bin/bash -c"
            args: "cat"
            alwaysPullImage: false
            runAsUser: 0
            ttyEnabled: true
            resourceRequestCpu: "1"
            resourceRequestMemory: "256Mi"
            resourceLimitCpu: "2"
            resourceLimitMemory: "1Gi"
        volumes:
          - secretVolume:
              mountPath: /root/.docker/
              secretName: gitea-docker-credentials-secret
              defaultMode: 256
          - secretVolume:
              mountPath: /root/.kube/
              secretName: kube-credentials-secret
              defaultMode: 256
        yamlMergeStrategy: merge
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            securityContext:
              runAsUser: 0
            containers:
              - name: jnlp
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
              - name: k8s
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
    python3: |
      - name: python3
        label: jenkins-python3
        serviceAccount: jenkins
        showRawYaml: false
        inheritFrom: default
        containers:
          - name: python3
            image: python:3-alpine
            command: "/bin/sh -c"
            args: "cat"
            alwaysPullImage: false
            runAsUser: 0
            ttyEnabled: true
            resourceRequestCpu: "500m"
            resourceRequestMemory: "256Mi"
            resourceLimitCpu: "1"
            resourceLimitMemory: "500Mi"
        yamlMergeStrategy: merge
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            securityContext:
              runAsUser: 0
            containers:
              - name: jnlp
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
              - name: python3
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
    jdk21: |
      - name: jdk21
        label: jenkins-jdk21
        serviceAccount: jenkins
        showRawYaml: false
        inheritFrom: default
        containers:
          - name: jdk21
            image: eclipse-temurin:21-jdk-alpine
            command: "/bin/sh -c"
            args: "cat"
            alwaysPullImage: false
            runAsUser: 0
            ttyEnabled: true
            resourceRequestCpu: "1"
            resourceRequestMemory: "256Mi"
            resourceLimitCpu: "2"
            resourceLimitMemory: "1Gi"
        yamlMergeStrategy: merge
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            securityContext:
              runAsUser: 0
            containers:
              - name: jnlp
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
              - name: jdk21
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates &&
                          ${JAVA_HOME}/bin/keytool -import -cacerts -alias rootCA -noprompt -storepass changeit -file /usr/local/share/ca-certificates/rootCA.crt"
    node20: |
      - name: node20
        label: jenkins-node20
        serviceAccount: jenkins
        showRawYaml: false
        inheritFrom: default
        containers:
          - name: node20
            image: node:20-alpine
            command: "/bin/sh -c"
            args: "cat"
            alwaysPullImage: false
            runAsUser: 0
            ttyEnabled: true
            resourceRequestCpu: "1"
            resourceRequestMemory: "256Mi"
            resourceLimitCpu: "2"
            resourceLimitMemory: "1Gi"
        yamlMergeStrategy: merge
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            securityContext:
              runAsUser: 0
            containers:
              - name: jnlp
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
    ssc5: |
      - name: ssc5
        label: jenkins-ssc5
        serviceAccount: jenkins
        showRawYaml: false
        inheritFrom: default
        containers:
          - name: ssc5
            image: sonarsource/sonar-scanner-cli:5
            command: "/bin/sh -c"
            args: "cat"
            alwaysPullImage: false
            runAsUser: 0
            ttyEnabled: true
            resourceRequestCpu: "1"
            resourceRequestMemory: "256Mi"
            resourceLimitCpu: "2"
            resourceLimitMemory: "1Gi"
        yamlMergeStrategy: merge
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            securityContext:
              runAsUser: 0
            containers:
              - name: jnlp
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
              - name: ssc5
                lifecycle:
                  postStart:
                    exec:
                      command:
                        - "/bin/sh"
                        - "-c"
                        - "mkdir -p /usr/local/share/ca-certificates && 
                          ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt && 
                          update-ca-certificates"
