---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-sonar-cache-maven
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pv-jenkins-sonar-cache-maven
