apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-npm
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pv-jenkins-npm
