apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-controller
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: pv-jenkins-controller
