---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-gradle
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-ssd-0-delete-retain
