apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-gradle
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.hitesh.com
    path: "/mnt/nfs/hdd_0/pv-jenkins-gradle"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-gradle
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ''
  volumeName: pv-jenkins-gradle