apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-maven
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.hitesh.com
    path: "/mnt/nfs/ssd_0/pv-jenkins-maven"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-maven
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ''
  volumeName: pv-jenkins-maven