apiVersion: v1
kind: Secret
metadata:
  name: jenkins-agent-post-start
  namespace: jenkins
type: Opaque
stringData:
  jnlp.sh: |
    mkdir -p /usr/local/share/ca-certificates
    ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
    update-ca-certificates
    echo "finished post start command"
  kaniko.sh: |
    mkdir -p /usr/local/share/ca-certificates
    ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
    echo "finished post start command"
  k8s.sh: |
    mkdir -p /usr/local/share/ca-certificates
    ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
    update-ca-certificates
    echo "finished post start command"
  python3.sh: |
    mkdir -p /usr/local/share/ca-certificates
    ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
    update-ca-certificates
    echo "finished post start command"
  jdk21.sh: |
    mkdir -p /usr/local/share/ca-certificates
    ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
    update-ca-certificates
    ${JAVA_HOME}/bin/keytool -import -cacerts -alias rootCA -noprompt -storepass changeit -file /usr/local/share/ca-certificates/rootCA.crt
    echo "finished post start command"
  node20.sh: |
    mkdir -p /usr/local/share/ca-certificates
    ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
    update-ca-certificates
    echo "finished post start command"
  ssc5.sh: |
    mkdir -p /usr/local/share/ca-certificates
    ln -sf /mnt/ca-certificates/custom/rootCA.crt /usr/local/share/ca-certificates/rootCA.crt
    update-ca-certificates
    mkdir -p /opt/sonar-scanner/.sonar
    ln -sf /root/.sonar/cache /opt/sonar-scanner/.sonar/cache
    echo "finished post start command"
