---
- name: Ensure group exists {{ kubernetes_user }}
  ansible.builtin.group:
    name: "{{ kubernetes_user }}"
    state: present

- name: Create the user account {{ kubernetes_user }}
  ansible.builtin.user:
    name: "{{ kubernetes_user }}"
    append: true
    state: present
    shell: /bin/bash
    create_home: true
    groups:
      - "{{ kubernetes_user }}"

- name: Allow to use sudo without needing a password user {{ kubernetes_user }}
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    line: "{{ kubernetes_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: Set up authorized keys for the user {{ kubernetes_user }}
  ansible.posix.authorized_key:
    user: "{{ kubernetes_user }}"
    state: present
    key: "{{ item }}"
  with_file: "{{ k8s_node_ssh_id_rsa_pubs }}"
