---
- name: Mount NFS volume ssd_0
  ansible.posix.mount:
    src: "{{ k8s_node_nfs_server }}:/mnt/nfs/ssd_0"
    path: "/home/{{ kubernetes_user }}/nfs/ssd_0"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
  when: k8s_node_nfs_server is defined
  changed_when: false

- name: Mount NFS volume hdd_0
  ansible.posix.mount:
    src: "{{ k8s_node_nfs_server }}:/mnt/nfs/hdd_0"
    path: "/home/{{ kubernetes_user }}/nfs/hdd_0"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
  when: k8s_node_nfs_server is defined
  changed_when: false

- name: Unmount NFS volume ssd_0
  ansible.posix.mount:
    src: "{{ k8s_node_nfs_server }}:/mnt/nfs/ssd_0"
    path: "/home/{{ kubernetes_user }}/nfs/ssd_0"
    opts: rw,sync,hard
    state: absent
    fstype: nfs
  when: k8s_node_nfs_server is defined
  changed_when: false

- name: Unmount NFS volume hdd_0
  ansible.posix.mount:
    src: "{{ k8s_node_nfs_server }}:/mnt/nfs/hdd_0"
    path: "/home/{{ kubernetes_user }}/nfs/hdd_0"
    opts: rw,sync,hard
    state: absent
    fstype: nfs
  when: k8s_node_nfs_server is defined
  changed_when: false

- name: Remove unused directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/{{ kubernetes_user }}/nfs"
  changed_when: false
