- name: Check for existing cluster crt
  ansible.builtin.stat:
    path: /etc/containerd/config.toml
  register: result
  changed_when: false

- name: Make sure the folder exists => /etc/containerd
  ansible.builtin.file:
    path: /etc/containerd
    state: directory

- name: Get defaults from containerd.
  ansible.builtin.command: containerd config default
  changed_when: not result.stat.exists
  register: containerd_config_default

- name: Prepare containerd/config.toml from default config
  ansible.builtin.copy:
    dest: "{{ tmpdir }}/containerd_config.toml"
    content: "{{ containerd_config_default.stdout }}"
  when: containerd_config_default is changed

- name: Set Cgroup driver to systemd
  ansible.builtin.lineinfile:
    insertafter: '.*\[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options\]$'
    line: '          SystemdCgroup = true'
    state: present
    path: "{{ tmpdir }}/containerd_config.toml"
  when: containerd_config_default is changed

- name: Make sure  SystemdCgroup = false is not set
  ansible.builtin.lineinfile:
    path: "{{ tmpdir }}/containerd_config.toml"
    state: absent
    line: '            SystemdCgroup = false'
  when: containerd_config_default is changed

- name: Copy config.toml to /etc/containerd
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tmpdir }}/containerd_config.toml"
    dest: /etc/containerd/config.toml
  when: containerd_config_default is changed
  notify: 
    - restart containerd

- name: Cleanup temporary file
  ansible.builtin.file:
    path: "{{ tmpdir }}/containerd_config.toml"
    state: absent
  when: containerd_config_default is changed
