- name: Add an apt signing key for Kubernetes
  ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor --batch --yes -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
    state: present
    filename: kubernetes

- name: Install Kubernetes binaries
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet=1.29.0-1.1
      - kubeadm=1.29.0-1.1
      - kubectl=1.29.0-1.1
  
- name: Hold Kubernetes binaries
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items: 
    - kubelet
    - kubeadm
    - kubectl
  notify: 
    - restart kubelet

- name: Make sure the folder exists => /var/lib/kubelet/config.d
  ansible.builtin.file:
    path: /var/lib/kubelet/config.d
    state: directory

- name: Copy /etc/default/kubelet file
  ansible.builtin.copy:
    src: "files/etc/default/kubelet"
    dest: "/etc/default/kubelet"
  notify: 
    - restart kubelet

- name: Copy custom kubelet config files
  ansible.builtin.copy:
    src: "files/var/lib/kubelet/config.d/{{ item }}"
    dest: "/var/lib/kubelet/config.d/{{ item }}"
  with_items: 
    - 01-custom.conf
  notify: 
    - restart kubelet