---
# tasks file for k8s_node
- name: Execute role k8s_node
  become: true
  become_user: root
  block:
    - name: Create User
      ansible.builtin.include_tasks: 01_kube_sudoer.yml

    - name: Mount shared NFS
      ansible.builtin.include_tasks: 02_kube_nfs_mount.yml

    - name: Enable modprobe Modules
      ansible.builtin.include_tasks: 03_kube_modprobe.yml

    - name: Disable Swap
      ansible.builtin.include_tasks: 04_kube_disable_swap.yml

    - name: Configure Sysctl
      ansible.builtin.include_tasks: 05_kube_configure_sysctl.yml

    - name: Configure Containerd
      ansible.builtin.include_tasks: 06_kube_configure_containerd.yml

    - name: Configure Crictl
      ansible.builtin.include_tasks: 07_kube_configure_crictl.yml

    - name: Install Kubernetes
      ansible.builtin.include_tasks: 08_kube_install_binaries.yml
