---
# tasks file for k8s_grafana
- name: Execute grafana role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Install prereq for grafana
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/grafana_namespace.yml
          - files/pvc_grafana.yml

    - name: Install prereq for grafana
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - secret/grafana_admin_secret.j2

    - name: Add Grafana helm repository
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Copy values file
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "{{ k8s_grafana_tmpdir }}/{{ item }}"
        mode: preserve
      changed_when: false
      with_items:
        - grafana_values.yml

    - name: Copy values file
      ansible.builtin.template:
        src: values/grafana_values_var.j2
        dest: "{{ k8s_grafana_tmpdir }}/grafana_values_var.yml"
        mode: preserve
      changed_when: false

    - name: Deploy latest version of grafana chart
      kubernetes.core.helm:
        name: grafana
        chart_ref: grafana/grafana
        chart_version: 8.10.0
        update_repo_cache: true
        release_namespace: grafana-system
        create_namespace: false
        values_files:
          - "{{ k8s_grafana_tmpdir }}/grafana_values.yml"
          - "{{ k8s_grafana_tmpdir }}/grafana_values_var.yml"
        wait: true
        timeout: "10m0s"
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ k8s_grafana_tmpdir }}/grafana_values.yml"
        - "{{ k8s_grafana_tmpdir }}/grafana_values_var.yml"
      changed_when: false

    - name: Install ingress internal
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - ingress/grafana_ingress_internal.j2

    - name: Install common dashboards grafana
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - dashboards/kubernetes_views_global_dashboard.yml
          - dashboards/kubernetes_views_namespace_dashboard.yml
          - dashboards/kubernetes_views_nodes_dashboard.yml
          - dashboards/kubernetes_views_pods_dashboard.yml
          - dashboards/node_exporter_full_dashboard.yml
          - dashboards/mongodb_database_dashboard.yml
          - dashboards/postgresql_database_dashboard.yml
          - dashboards/rabbitmq_overview_dashboard.yml
          - dashboards/node_js_application_dashboard.yml
          - dashboards/spring_boot_observability_dashboard.yml
