apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nfs-server
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nfs-server
spec:
  endpoints:
    - interval: 30s
      port: http-metrics
      path: /metrics
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/name: nfs-server
