---
# tasks file for k8s_immich
- name: Execute immich role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Install prereq for immich
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/immich_namespace.yml
          - files/pvc_immich.yml
          - files/pvc_immich_postgresql_primary.yml
          - files/svc_immich_machine_learning.yml

    - name: Install prereq for immich
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - ingress/immich_ingress.j2

    - name: Add immich helm repository
      kubernetes.core.helm_repository:
        name: immich
        repo_url: https://immich-app.github.io/immich-charts

    - name: Copy values file
      ansible.builtin.copy:
        src: files/immich_values.yml
        dest: "{{ k8s_immich_tmpdir }}/immich_values.yml"
        mode: preserve
      changed_when: false

    - name: Deploy latest version of immich chart
      kubernetes.core.helm:
        name: immich
        chart_ref: immich/immich
        chart_version: 0.8.5
        update_repo_cache: true
        release_namespace: immich-system
        create_namespace: false
        values_files:
          - "{{ k8s_immich_tmpdir }}/immich_values.yml"
        wait: true
        timeout: "10m0s"
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ k8s_immich_tmpdir }}/immich_values.yml"
      changed_when: false

    - name: Install ingress internal
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - ingress/immich_ingress_internal.j2
