---
# tasks file for k8s_gitea
- name: Execute casdoor role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Create volume directory on nfs if it does not exist
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0777'
        owner: 1000
        group: 1000
      with_items: 
        - "/home/{{ kubernetes_user }}/nfs/ssd_0/pv-casdoor-mysql-primary"

    # install prereqs
    - name: Install prereq for casdoor
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls: 
          - files/casdoor_namespace.yml
          - files/pvc_casdoor_mysql_primary.yml
          - files/casdoor_ingress.yml
          - files/casdoor_service.yml

    - name: Install prereq for gitea 2
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s: 
          - secret/casdoor_admin_secret.j2
          - secret/casdoor_mysql_secret.j2
          - config/casdoor_config.j2
          - config/casdoor_init_data.j2
          - secret/casdoor_custom_root_ca_cert.j2

    - name: Add Bitnami helm repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Copy values file
      ansible.builtin.copy:
        src: files/casdoor_mysql_values.yml
        dest: "{{ tmpdir }}/casdoor_mysql_values.yml"
      changed_when: false

    - name: Deploy latest version of mysql chart
      kubernetes.core.helm:
        name: casdoor-mysql
        chart_ref: bitnami/mysql
        chart_version: 9.12.5
        update_repo_cache: true
        release_namespace: casdoor-system
        create_namespace: false
        values_files:
          - "{{ tmpdir }}/casdoor_mysql_values.yml"
        wait: true
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ tmpdir }}/casdoor_mysql_values.yml"
      changed_when: false

    # install casdoor deployment
    - name: Install casdoor
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls: 
          - files/casdoor_deployment.yml
