loki:
  # Should authentication be enabled
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: "filesystem"

# Configuration for the single binary node(s)
singleBinary:
  replicas: 1
  persistence:
    # -- Enable StatefulSetAutoDeletePVC feature
    enableStatefulSetAutoDeletePVC: true
    # -- Enable persistent disk
    enabled: true
    # -- Size of persistent disk
    size: 1Gi
    # -- Storage class to be used.
    # If defined, storageClassName: <storageClass>.
    # If set to "-", storageClassName: "", which disables dynamic provisioning.
    # If empty or set to null, no storageClassName spec is
    # set, choosing the default provisioner (gp2 on AWS, standard on GKE, AWS, and OpenStack).
    storageClass: "nfs-client-ssd-0"
  # -- Resource requests and limits for the single binary
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi

# Configuration for the gateway
gateway:
  # -- Resource requests and limits for the gateway
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  # Gateway ingress configuration
  ingress:
    # -- Specifies whether an ingress for the gateway should be created
    enabled: true
    # -- Ingress Class Name. MAY be required for Kubernetes versions >= 1.18
    ingressClassName: "nginx"
    # -- Annotations for the gateway ingress
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # -- Hosts configuration for the gateway ingress, passed through the `tpl` function to allow templating
    # hosts: --> template
    # -- TLS configuration for the gateway ingress. Hosts passed through the `tpl` function to allow templating
    tls: []
