---
# tasks file for k8s_teardown
- name: Execute k8s cluster k8s_teardown
  become: true
  become_user: root
  block:
    - name: Check for existing cluster crt
      ansible.builtin.stat:
        path: /etc/kubernetes/pki/ca.crt
      register: result
      changed_when: false

    - name: Restart containerd
      ansible.builtin.service:
        name: "containerd"
        state: "restarted"
        enabled: true
      when: result.stat.exists

    - name: Reset kubeadm node
      ansible.builtin.command: kubeadm reset -f
      when: result.stat.exists
      changed_when: true

    - name: Clean IP tables
      ansible.builtin.shell: |
        iptables -F
        iptables -t nat -F
        iptables -t mangle -F
        iptables -X
      when: result.stat.exists
      changed_when: true

    # - name: Reset IPVS tables
    #   command: ipvsadm -C
    #   when: result.stat.exists

    - name: Remove file => /home/kube/.kube/config
      ansible.builtin.file:
        path: /home/kube/.kube/config
        state: absent
      when: result.stat.exists

    - name: Delete local kube config
      delegate_to: localhost
      ansible.builtin.file:
        path: /home/hitesh/.kube/config
        state: absent
      when: result.stat.exists

    - name: Reboot
      ansible.builtin.reboot:
      when: result.stat.exists
      changed_when: false
