---
# tasks file for k8s_gitea
- name: Execute gitea role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Install prereq for gitea
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/gitea_namespace.yml
          - files/pvc_gitea.yml
          - files/pvc_gitea_postgresql_ha_primary.yml

    - name: Install prereq for gitea
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - secret/gitea_admin_secret.j2
          - secret/gitea_gpg_key.j2
          - secret/gitea_oauth_secret.j2

    - name: Add Gitea helm repository
      kubernetes.core.helm_repository:
        name: gitea-charts
        repo_url: https://dl.gitea.io/charts/

    - name: Copy values file
      ansible.builtin.copy:
        src: files/gitea_values.yml
        dest: "{{ k8s_gitea_tmpdir }}/gitea_values.yml"
        mode: preserve
      changed_when: false

    - name: Copy values file
      ansible.builtin.template:
        src: values/gitea_values_var.j2
        dest: "{{ k8s_gitea_tmpdir }}/gitea_values_var.yml"
        mode: preserve
      changed_when: false

    - name: Deploy latest version of gitea chart
      kubernetes.core.helm:
        name: gitea
        chart_ref: gitea-charts/gitea
        chart_version: 11.0.0
        update_repo_cache: true
        release_namespace: gitea-system
        create_namespace: false
        values_files:
          - "{{ k8s_gitea_tmpdir }}/gitea_values.yml"
          - "{{ k8s_gitea_tmpdir }}/gitea_values_var.yml"
        wait: true
        timeout: "10m0s"
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ k8s_gitea_tmpdir }}/gitea_values.yml"
        - "{{ k8s_gitea_tmpdir }}/gitea_values_var.yml"
      changed_when: false

    - name: Install ingress internal
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - ingress/gitea_ingress_internal.j2

    - name: Install grafana dashboard for gitea
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        utility_k8s_install_ymls:
          - files/gitea_grafana_dashboard.yml
