---
- name: Mount NFS volume ssd_0
  ansible.posix.mount:
    src: "{{ k8s_cluster_nfs_server }}:/mnt/nfs/ssd_0"
    path: "/home/{{ kubernetes_user }}/nfs/ssd_0"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
  when: k8s_cluster_nfs_server is defined
  changed_when: false
