---
# tasks file for k8s_cluster
- name: Create .kube directory
  ansible.builtin.file:
    path: "/home/{{ kubernetes_user }}/.kube"
    state: directory
    mode: 0755
    owner: "{{ kubernetes_user }}"
    group: "{{ kubernetes_user }}"

- name: Check for existing cluster crt
  ansible.builtin.stat:
    path: /etc/kubernetes/pki/ca.crt
  register: result
  changed_when: false

- name: Initialize the cluster
  become: true
  become_user: root
  ansible.builtin.command: kubeadm init --control-plane-endpoint {{ k8s_cluster_control_plane_endpoint | quote }} --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ k8s_cluster_api_server_advertise_address }}
  args:
    chdir: $HOME
    creates: cluster_initialized.txt
  when: not result.stat.exists

- name: Copies admin.conf to user's kube config
  become: true
  become_user: root
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ kubernetes_user }}/.kube/config"
    remote_src: true
    owner: "{{ kubernetes_user }}"
    group: "{{ kubernetes_user }}"
    mode: 0600
  when: not result.stat.exists

- name: Copies config to user's local
  ansible.builtin.fetch:
    src: "/home/{{ kubernetes_user }}/.kube/config"
    dest: /home/hitesh/.kube/config
    flat: true
  when: not result.stat.exists

- name: Correct Permission of kube config
  become: true
  become_user: root
  delegate_to: localhost
  ansible.builtin.file:
    path: /home/hitesh/.kube/config
    owner: hitesh
    group: hitesh
    mode: 0600
  when: not result.stat.exists

- name: Get the cert for joining the master nodes
  become: true
  become_user: root
  ansible.builtin.shell: set -o pipefail && kubeadm init phase upload-certs --upload-certs | grep -vw -e certificate -e Namespace
  register: kubernetes_join_cert_key
  when: true
  changed_when: false

- name: Get the token for joining the worker nodes
  become: true
  become_user: root
  ansible.builtin.command: kubeadm token create  --print-join-command
  register: kubernetes_join_command
  when: true
  changed_when: false

- name: Copy master join command to nfs location => /home/kube/nfs/ssd_0/kubernetes_master_join_command
  ansible.builtin.copy:
    content: "{{ kubernetes_join_command.stdout_lines[0] }} --control-plane --certificate-key {{ kubernetes_join_cert_key.stdout }}"
    dest: "/home/{{ kubernetes_user }}/nfs/ssd_0/kubernetes_master_join_command"
    mode: "0777"
  when: true and not ansible_check_mode
  changed_when: false

- name: Copy worker join command to nfs location => /home/kube/nfs/ssd_0/kubernetes_join_command
  ansible.builtin.copy:
    content: "{{ kubernetes_join_command.stdout_lines[0] }}"
    dest: "/home/{{ kubernetes_user }}/nfs/ssd_0/kubernetes_join_command"
    mode: "0777"
  when: true and not ansible_check_mode
  changed_when: false
