---
- name: Check for existing cluster crt
  ansible.builtin.stat:
    path: /etc/kubernetes/pki/ca.crt
  register: cluster_crt
  changed_when: false

- name: Check for existing join command
  ansible.builtin.stat:
    path: "/home/{{ kubernetes_user }}/nfs/ssd_0/kubernetes_join_command"
  register: join_command
  changed_when: false

- name: Copy join command from nfs share to local.
  ansible.builtin.copy:
    src: "/home/{{ kubernetes_user }}/nfs/ssd_0/kubernetes_join_command"
    dest: "{{ tmpdir }}/kubernetes_join_command"
    mode: 0777
    remote_src: true
  when: not cluster_crt.stat.exists and join_command.stat.exists

- name: Join the Worker nodes to the cluster
  become: true
  become_user: root
  ansible.builtin.command: "sh {{ tmpdir }}/kubernetes_join_command"
  register: joined_or_not
  when: not cluster_crt.stat.exists and join_command.stat.exists
