---
- name: Mount shared directory
  become: true
  become_user: root
  block:
    - name: Mount NFS share
      ansible.builtin.include_tasks: 00_nfs_mount.yml

- name: Execute role k8s_cluster
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Create Cluster
      ansible.builtin.include_tasks: 01_master_init.yml
      when: inventory_hostname == 'k8s-master-01'

    - name: Run join for other master nodes
      ansible.builtin.include_tasks: 02_master_join.yml
      when: inventory_hostname in groups['k8s_master'] and inventory_hostname != 'k8s-master-01'

    - name: Run join for workers
      ansible.builtin.include_tasks: 03_worker_join.yml
      when: inventory_hostname in groups['k8s_worker']

# - name: Reconfigure kubelets
#   include_tasks: 05_reconfigure_kubelet.yml

- name: Cleanup
  become: true
  become_user: root
  block:
    - name: Cleanup
      ansible.builtin.include_tasks: 09_cleanup.yml
