galaxy_info:
  author: Hitesh Nayak
  description: developer
  company: '-'
  license: license (MIT)
  min_ansible_version: '2.1'
  platforms:
  - name: Ubuntu
    versions:
    - all
  galaxy_tags: []
dependencies: []
