---
daemonset:
  # -- Deploys Promtail as a DaemonSet
  enabled: true

image:
  # -- The Docker registry
  registry: docker.io
  # -- Docker image repository
  repository: hiteshnayak305/promtail
  # -- Overrides the image tag whose default is the chart's appVersion
  # tag: null

# -- Resource requests and limits
resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 100Mi

# -- Tolerations for pods. By default, pods will be scheduled on master/control-plane nodes.
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

# ServiceMonitor configuration
serviceMonitor:
  # -- If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: false

# Extra volumes to be added in addition to those specified under `defaultVolumes`.
extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal

# Extra volume mounts together. Corresponds to `extraVolumes`.
extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true

# -- Section for crafting Promtails config file. The only directly relevant value is `config.file`
# which is a templated string that references the other values and snippets below this key.
# @default -- See `values.yaml`
config:
  # -- Enable Promtail config from Helm chart
  # Set `configmap.enabled: true` and this to `false` to manage your own Promtail config
  # See default config in `values.yaml`
  enabled: true
  # -- The port of the Promtail server
  # Must be reference in `config.file` to configure `server.http_listen_port`
  # See default config in `values.yaml`
  serverPort: 3101
  # -- The config of clients of the Promtail server
  # Must be reference in `config.file` to configure `clients`
  # @default -- See `values.yaml`
  # clients: -> template
  # -- A section of reusable snippets that can be reference in `config.file`.
  # Custom snippets may be added in order to reduce redundancy.
  # This is especially helpful when multiple `kubernetes_sd_configs` are use which usually have large parts in common.
  # @default -- See `values.yaml`
  snippets:
    # -- You can put here any additional scrape configs you want to add to the config file.
    # @default -- empty
    extraScrapeConfigs: |
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ["__journal__systemd_unit"]
            target_label: "unit"
          - source_labels: ["__journal__hostname"]
            target_label: host
          - source_labels: ["__journal_priority_keyword"]
            target_label: level
          - source_labels: ["__journal_syslog_identifier"]
            target_label: syslog_identifier
        pipeline_stages:
          - match:
              selector:  '{unit="promtail.service"}'
              action: drop
