## This chart relies on the common library chart from bjw-s
## You can find it at https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
## Refer there for more detail about the supported values

image:
  tag: v1.99.0

immich:
  persistence:
    # Main data store for all photos shared between different components.
    library:
      # Automatically creating the library volume is not supported by this chart
      # You have to specify an existing PVC to use
      existingClaim: "pvc-immich"

# Dependencies

postgresql:
  enabled: true
  ## Bitnami PostgreSQL image version
  ## ref: https://hub.docker.com/r/bitnami/postgresql/tags/
  ## @param image.registry [default: REGISTRY_NAME] PostgreSQL image registry
  ## @param image.repository [default: REPOSITORY_NAME/postgresql] PostgreSQL image repository
  ## @skip image.tag PostgreSQL image tag (immutable tags are recommended)
  ## @param image.digest PostgreSQL image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
  ## @param image.pullPolicy PostgreSQL image pull policy
  ## @param image.pullSecrets Specify image pull secrets
  ## @param image.debug Specify if debug values should be set
  ##
  image:
    registry: docker.io
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: immich
        postgresPassword: immich
  ## @section PostgreSQL Primary parameters
  ##
  primary:
    persistence:
      enabled: true
      storageClass: "-"
      existingClaim: "pvc-immich-postgresql-primary"
      accessModes:
        - ReadWriteOnce
      size: 1G

  ## @section Metrics Parameters
  ##

  metrics:
    ## @param metrics.enabled Start a prometheus exporter
    ##
    enabled: true

redis:
  enabled: true
  ## Bitnami Redis&reg; image
  ## ref: https://hub.docker.com/r/bitnami/redis/tags/
  ## @param image.registry [default: REGISTRY_NAME] Redis&reg; image registry
  ## @param image.repository [default: REPOSITORY_NAME/redis] Redis&reg; image repository
  ## @skip image.tag Redis&reg; image tag (immutable tags are recommended)
  ## @param image.digest Redis&reg; image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
  ## @param image.pullPolicy Redis&reg; image pull policy
  ## @param image.pullSecrets Redis&reg; image pull secrets
  ## @param image.debug Enable image debug mode
  ##
  image:
    registry: docker.io
    repository: bitnami/redis
    tag: 7.2-debian-11
  architecture: standalone
  auth:
    enabled: false
  global:
    storageClass: "nfs-client-ssd-0"
  master:
    persistence:
      size: 1Gi

# Immich components

server:
  ingress:
    main:
      enabled: false

microservices:
  enabled: true
  persistence:
    geodata-cache:
      enabled: true
      size: 1Gi
      # Optional: Set this to pvc to avoid downloading the geodata every start.
      type: pvc
      accessMode: ReadWriteMany
      storageClass: "nfs-client-ssd-0"

machine-learning:
  enabled: true
  persistence:
    cache:
      enabled: true
      size: 10Gi
      # Optional: Set this to pvc to avoid downloading the ML models every start.
      type: pvc
      accessMode: ReadWriteMany
      storageClass: "nfs-client-ssd-0"
