---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich
  namespace: immich-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 80Gi
  storageClassName: nfs-ssd-0-retain-retain
