---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-immich
  namespace: immich-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: pv-immich
