---
# -- Define the amount of instances
replicas: 1

# -- Number of old history to retain to allow rollback (If not set, default Kubernetes value is set to 10)
revisionHistoryLimit: 1

tempo:
  repository: grafana/tempo
  tag: ""
  pullPolicy: IfNotPresent

  updateStrategy: RollingUpdate
  memBallastSizeMbs: 256
  retention: 168h
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi

  # -- If true, Tempo will report anonymous usage data about the shape of a deployment to Grafana Labs
  reportingEnabled: false

serviceMonitor:
  enabled: true

persistence:
  enabled: true
  storageClassName: nfs-ssd-0-delete-retain
  accessModes:
    - ReadWriteOnce
  size: 10Gi
