---
# tasks file for k8s_tempo
- name: Execute tempo role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Add tempo helm repository
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Copy values file
      ansible.builtin.copy:
        src: files/tempo_values.yml
        dest: "{{ k8s_tempo_tmpdir }}/tempo_values.yml"
        mode: "0777"
      changed_when: false

    - name: Deploy latest version of tempo chart
      kubernetes.core.helm:
        name: tempo
        chart_ref: grafana/tempo
        chart_version: 1.18.3
        update_repo_cache: true
        release_namespace: tempo-system
        create_namespace: true
        values_files:
          - "{{ k8s_tempo_tmpdir }}/tempo_values.yml"
        wait: true
        timeout: "10m0s"
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ k8s_tempo_tmpdir }}/tempo_values.yml"
      changed_when: false

    - name: Install ingress
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - ingress/tempo_ingress.j2
          - ingress/tempo_ingress_internal.j2

    - name: Install grafana datasource
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        utility_k8s_install_j2s:
          - configmap/datasource_configmap.j2
