---
# tasks file for k8s_loki
- name: Execute loki role
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    - name: Add loki helm repository
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts

    - name: Add bitnami kubernetes event exporter helm repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: https://charts.bitnami.com/bitnami

    - name: Copy values file
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "{{ tmpdir }}/{{ item }}"
        mode: "0777"
      with_items:
        - loki_values.yml
        - loki_promtail_values.yml
        - loki_kubernetes_event_exporter_values.yml
      changed_when: false

    - name: Copy values file
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ tmpdir }}/{{ item | basename | splitext | first }}.yml"
        mode: "0777"
      changed_when: false
      with_items:
        - values/loki_values_var.j2
        - values/loki_promtail_values_var.j2
        - values/loki_kubernetes_event_exporter_values_var.j2

    - name: Deploy latest version of loki chart
      kubernetes.core.helm:
        name: loki
        chart_ref: grafana/loki
        chart_version: 6.22.0
        update_repo_cache: true
        release_namespace: loki-system
        create_namespace: true
        values_files:
          - "{{ tmpdir }}/loki_values.yml"
          - "{{ tmpdir }}/loki_values_var.yml"
        wait: true
        timeout: "10m0s"
      when: not ansible_check_mode

    - name: Deploy latest version of promtail chart
      kubernetes.core.helm:
        name: promtail
        chart_ref: grafana/promtail
        chart_version: 6.16.6
        update_repo_cache: true
        release_namespace: loki-system
        create_namespace: false
        values_files:
          - "{{ tmpdir }}/loki_promtail_values.yml"
          - "{{ tmpdir }}/loki_promtail_values_var.yml"
        wait: true
        timeout: "10m0s"
      when: not ansible_check_mode

    - name: Deploy latest version of kubernetes event exporter chart
      kubernetes.core.helm:
        name: kubernetes-event-exporter
        chart_ref: bitnami/kubernetes-event-exporter
        chart_version: 3.2.15
        update_repo_cache: true
        release_namespace: loki-system
        create_namespace: false
        values_files:
          - "{{ tmpdir }}/loki_kubernetes_event_exporter_values.yml"
          - "{{ tmpdir }}/loki_kubernetes_event_exporter_values_var.yml"
        wait: true
        timeout: "10m0s"
      when: not ansible_check_mode

    - name: Remove temp files (delete file)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tmpdir }}/loki_values.yml"
        - "{{ tmpdir }}/loki_values_var.yml"
        - "{{ tmpdir }}/loki_promtail_values.yml"
        - "{{ tmpdir }}/loki_promtail_values_var.yml"
        - "{{ tmpdir }}/loki_kubernetes_event_exporter_values.yml"
        - "{{ tmpdir }}/loki_kubernetes_event_exporter_values_var.yml"
      changed_when: false

    - name: Install ingress internal
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s:
          - ingress/loki_ingress_internal.j2

    - name: Install datasource for loki
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_j2
      vars:
        k8s_install_j2s:
          - cm/loki_datasource_configmap.j2

    - name: Install grafana dashboards
      ansible.builtin.include_role:
        name: utility
        tasks_from: k8s_install_yml
      vars:
        k8s_install_ymls:
          - dashboards/logs_app_dashboard.yml
