---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarqube
  namespace: sonarqube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-ssd-0-retain-retain
