apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarqube
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: nfs.hitesh.com
    path: "/mnt/nfs/ssd_0/pv-sonarqube"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarqube
  namespace: sonarqube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ''
  volumeName: pv-sonarqube