---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarqube-postgresql-primary
  namespace: sonarqube-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv-sonarqube-postgresql-primary
