---
# handlers file for k8s_node
- name: Restart Containerd
  become: true
  become_user: root
  ansible.builtin.service:
    name: "containerd"
    state: "restarted"
    enabled: true

- name: Restart Kubelet
  become: true
  ansible.builtin.service:
    name: kubelet
    state: restarted
    enabled: true
