---
# vars file for utility

# utility_tmpdir
utility_tmpdir: /tmp

# hosts file path
utility_hosts_file_path: /etc/hosts

# sshd config path
utility_sshd_config_path: /etc/ssh/sshd_config

# sudoers file path
utility_sudoers_file_path: /etc/sudoers

# user CA certificates path
utility_usr_ca_cert_path: /usr/local/share/ca-certificates

# htop config file path
utility_htop_config_file_path: ~/.config/htop
