---
# defaults file for k8s_jenkins
# tmpdir
tmpdir: /tmp

# admin cred
jenkins_admin_username: admin
jenkins_admin_password: password

# ca crt
root_ca_crt: ''

# gitea registry
gitea_docker_config_json: '{}'
gitea_docker_config_json_base64: ''