apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-authentik-postgresql-primary
  namespace: authentik-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv-authentik-postgresql-primary
