---
# handlers file for nfs_server
- name: exportfs a
  become: true
  become_user: root
  ansible.builtin.shell:
    cmd: exportfs -a

- name: restart nfs-kernel-server
  become: true
  become_user: root
  ansible.builtin.service:
    name: "nfs-kernel-server"
    state: "restarted"
    enabled: true
