---
# handlers file for nfs_server
- name: Exportfs a
  become: true
  become_user: root
  ansible.builtin.command: exportfs -a
  changed_when: true

- name: Restart nfs-kernel-server
  become: true
  become_user: root
  ansible.builtin.service:
    name: "nfs-kernel-server"
    state: "restarted"
    enabled: true
