---
- name: Ensuring available-modules config path exists
  ansible.builtin.file:
    dest: "{{ nginx_proxy_available_modules_config_file_path }}"
    owner: "root"
    group: "root"
    mode: 0755
    state: "directory"

- name: Install custom config file
  ansible.builtin.template:
    src: etc/nginx/modules-available/module_config.j2
    dest: "{{ nginx_proxy_available_modules_config_file_path }}/{{ nginx_proxy_nginx_domain }}"
    owner: "root"
    group: "root"
    mode: 0755
  register: config0

- name: Disable default http config file
  ansible.builtin.file:
    path: "{{ nginx_proxy_enabled_sites_config_file_path }}/default"
    state: absent
  register: config1

- name: Enable custom config file
  ansible.builtin.file:
    src: "{{ nginx_proxy_available_modules_config_file_path }}/{{ nginx_proxy_nginx_domain }}"
    dest: "{{ nginx_proxy_enabled_modules_config_file_path }}/{{ nginx_proxy_nginx_domain }}.conf"
    owner: "root"
    group: "root"
    mode: 0755
    state: link
  register: config2

- name: Test Configuration
  ansible.builtin.command: "nginx -t"
  when: config0 is changed or config1 is changed or config2 is changed
  changed_when: config0 is changed or config1 is changed or config2 is changed
  notify:
    - Restart Nginx
