---
- name: Execute Role Nginx Proxy
  become: true
  become_user: root
  block:
    - name: Install binaries
      ansible.builtin.include_tasks: 01_install_binaries.yml
    - name: Install configuration files
      ansible.builtin.include_tasks: 02_configure_proxy.yml
    - name: Install node exporter
      ansible.builtin.include_tasks: 03_configure_node_exporter.yml
