---
- name: Create coredns config manifest
  ansible.builtin.template:
    src: config-map/coredns.j2
    dest: "{{ tmpdir }}/coredns.yml"
  changed_when: false

- name: Install coredns config map
  kubernetes.core.k8s:
    state: present
    src: "{{ tmpdir }}/coredns.yml"
    wait: true
  register: config
  when: not ansible_check_mode

- name: Restart coredns if configuration changed
  ansible.builtin.shell: kubectl rollout restart deployment/coredns -n kube-system
  when: config is changed

- name: Remove temp files (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmpdir }}/coredns.yml"
  changed_when: false
