---
- name: Create kube proxy config manifest
  ansible.builtin.template:
    src: config-map/kube_proxy.j2
    dest: "{{ k8s_init_tmpdir }}/kube_proxy.yml"
    mode: "0777"
  changed_when: false

- name: Install kube proxy config map
  kubernetes.core.k8s:
    state: present
    src: "{{ k8s_init_tmpdir }}/kube_proxy.yml"
    wait: true
  when: not ansible_check_mode
  notify:
    - Restart kube-proxy

- name: Remove temp files (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ k8s_init_tmpdir }}/kube_proxy.yml"
  changed_when: false
