- name: Install Helm 3 Package
  become: true
  become_user: root
  block:
    - name: Add an apt signing key for Helm
      ansible.builtin.apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Adding apt repository for Helm
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm-stable-debian.list

    - name: Install Helm binary
      ansible.builtin.apt: 
        name: helm
        state: present
        update_cache: yes
      
    - name: Install APT Packages
      ansible.builtin.include_role:
        name: utility
        tasks_from: apt_install
      vars:
        apt_install:
          - git

- name: Install Helm diff 3.x.x
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    plugin_version: v3.8.1
    state: present
