- name: Install Helm 3 Package
  become: true
  become_user: root
  block:
    - name: Add an apt signing key for Helm
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/keyrings/helm.asc
        mode: "0644"
        force: true

    - name: Adding apt repository for Helm
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/helm.asc] https://baltocdn.com/helm/stable/debian/ all main
        state: present
        filename: helm-stable-debian

    - name: Install Helm binary
      ansible.builtin.apt:
        name: helm
        state: present
        update_cache: yes

    - name: Install APT Packages
      ansible.builtin.include_role:
        name: utility
        tasks_from: apt_install
      vars:
        apt_install:
          - git

- name: Remove Old Helm diff 3.x.x
  kubernetes.core.helm_plugin:
    plugin_name: diff
    state: absent
  changed_when: false

- name: Install Helm diff 3.x.x
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    plugin_version: v3.9.6
    state: present
  changed_when: false
