---
- name: Add Flannel helm repository
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/

- name: Install kube-flannel namespace
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    utility_k8s_install_ymls:
      - files/flannel_namespace.yml

- name: Copy values file
  ansible.builtin.copy:
    src: files/flannel_values.yml
    dest: "{{ k8s_init_tmpdir }}/flannel_values.yml"
    mode: "0777"
  changed_when: false

- name: Copy values file
  ansible.builtin.template:
    src: values/flannel_values_var.j2
    dest: "{{ k8s_init_tmpdir }}/flannel_values_var.yml"
    mode: "0777"
  changed_when: false

- name: Deploy latest version of flannel chart
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    chart_version: v0.26.6
    update_repo_cache: true
    release_namespace: kube-flannel
    create_namespace: false
    values_files:
      - "{{ k8s_init_tmpdir }}/flannel_values.yml"
      - "{{ k8s_init_tmpdir }}/flannel_values_var.yml"
    wait: true
    timeout: "10m0s"
  when: not ansible_check_mode

- name: Remove temp files (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ k8s_init_tmpdir }}/flannel_values.yml"
    - "{{ k8s_init_tmpdir }}/flannel_values_var.yml"
  changed_when: false
