- name: Add metalLB helm repository
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb

- name: Install metallb namespace
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    k8s_install_ymls:
      - files/metallb_namespace.yml

- name: Copy values file
  ansible.builtin.copy:
    src: files/metallb_values.yml
    dest: "{{ tmpdir }}/metallb_values.yml"
  changed_when: false

- name: Deploy latest version of MetalLB chart
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version: 0.14.3
    update_repo_cache: true
    release_namespace: metallb-system
    create_namespace: false
    values_files:
      - "{{ tmpdir }}/metallb_values.yml"
    wait: true
  when: not ansible_check_mode

- name: Remove temp files (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmpdir }}/metallb_values.yml"
  changed_when: false

- name: Install ip address pool and l2 advertisement file
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_j2
  vars:
    k8s_install_j2s:
      - crd/metallb_ip_address_pool.j2
      - crd/metallb_l2_advertisement.j2
