---
- name: Add jetstack helm repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Copy values file
  ansible.builtin.copy:
    src: files/cert_manager_values.yml
    dest: "{{ tmpdir }}/cert_manager_values.yml"
    mode: "0777"
  changed_when: false

- name: Deploy latest version of cert manager chart
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    chart_version: 1.16.2
    update_repo_cache: true
    release_namespace: cert-manager
    create_namespace: true
    values_files:
      - "{{ tmpdir }}/cert_manager_values.yml"
    wait: true
    timeout: "10m0s"
  when: not ansible_check_mode

- name: Remove temp files (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmpdir }}/cert_manager_values.yml"
  changed_when: false

- name: Install cluster issuer from ca certificate
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_j2
  vars:
    k8s_install_j2s:
      - secret/cert_manager_ca_key_pair.j2
      - crd/cert_manager_cluster_issuer_ca.j2

- name: Install grafana dashboard
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    k8s_install_ymls:
      - files/cert_manager_dashboard.yml
