- name: Install nginx system namespace
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    k8s_install_ymls:
      - files/nginx_ingress_namespace.yml

- name: Create certificates for nginx default tls
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_j2
  vars:
    k8s_install_j2s:
      - crd/cert_manager_certificate_ingress_nginx_default_tls.j2

- name: Add nginx-ingress helm repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: copy values files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: "{{ tmpdir }}/{{ item }}"
  changed_when: false
  with_items:
    - nginx_ingress_values.yml
    - nginx_ingress_internal_values.yml

- name: Deploy latest version of nginx-ingress chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: 4.10.0
    update_repo_cache: true
    release_namespace: nginx-system
    create_namespace: false
    values_files:
      - "{{ tmpdir }}/nginx_ingress_values.yml"
    wait: true
  when: not ansible_check_mode

- name: Deploy latest version of nginx-ingress chart (internal)
  kubernetes.core.helm:
    name: ingress-nginx-internal
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: 4.10.0
    update_repo_cache: true
    release_namespace: nginx-system
    create_namespace: false
    values_files:
      - "{{ tmpdir }}/nginx_ingress_values.yml"
      - "{{ tmpdir }}/nginx_ingress_internal_values.yml"
    wait: true
  when: not ansible_check_mode

- name: Remove temp files (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmpdir }}/nginx_ingress_values.yml"
    - "{{ tmpdir }}/nginx_ingress_internal_values.yml"
  changed_when: false
