- name: Install skooner namespace
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    k8s_install_ymls: 
      - files/skooner_namespace.yml

- name: Install skooner
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    k8s_install_urls: 
      - https://raw.githubusercontent.com/skooner-k8s/skooner/master/kubernetes-skooner.yaml

- name: Install ingress for skooner
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    k8s_install_ymls: 
      - files/skooner_ingress.yml
