---
- name: Add deliveryhero helm repository
  kubernetes.core.helm_repository:
    name: deliveryhero
    repo_url: https://raw.githubusercontent.com/deliveryhero/helm-charts/refs/heads/master/

- name: Copy values file
  ansible.builtin.copy:
    src: files/node_problem_detector_values.yml
    dest: "{{ k8s_init_tmpdir }}/node_problem_detector_values.yml"
    mode: "0777"
  changed_when: false

- name: Deploy latest version of node-problem-detector chart
  kubernetes.core.helm:
    name: node-problem-detector
    chart_ref: deliveryhero/node-problem-detector
    chart_version: 2.3.17
    update_repo_cache: true
    release_namespace: node-problem-detector
    create_namespace: true
    values_files:
      - "{{ k8s_init_tmpdir }}/node_problem_detector_values.yml"
    wait: true
    timeout: "10m0s"
  when: not ansible_check_mode

- name: Remove temp files (delete file)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ k8s_init_tmpdir }}/node_problem_detector_values.yml"
  changed_when: false

- name: Install grafana dashboard
  ansible.builtin.include_role:
    name: utility
    tasks_from: k8s_install_yml
  vars:
    utility_k8s_install_ymls:
      - files/node_problem_detector_dashboard.yml
