---
- name: Execute postinstallation for k8s
  become: true
  become_user: "{{ kubernetes_user }}"
  block:
    # - name: Configure coredns
    #   include_tasks: 00_config_coredns.yml

    # - name: Configure kube proxy
    #   include_tasks: 00_config_kube_proxy.yml

    - name: Installing Helm
      ansible.builtin.include_tasks: 01_install_helm.yml

    - name: Installing Flannel Network Plugin
      ansible.builtin.include_tasks: 02_install_flannel.yml

    - name: Installing MetalLB
      ansible.builtin.include_tasks: 03_install_metallb.yml

    - name: Installing Cert Manager
      ansible.builtin.include_tasks: 04_install_cert_manager.yml

    - name: Installing Nginx Ingress
      ansible.builtin.include_tasks: 05_install_nginx_ingress.yml

    - name: Installing Kubernetes Dashboard
      ansible.builtin.include_tasks: 06_install_kubernetes_dashboard.yml

    - name: Installing CSI NFS Driver & Provisioner
      ansible.builtin.include_tasks: 07_install_csi_nfs_driver.yml

    - name: Installing NFS Subdirectory External Provisioner
      ansible.builtin.include_tasks: 07_install_nfs-subdir-external-provisioner.yml

    - name: Installing Node Problem Detector
      ansible.builtin.include_tasks: 08_install_node_problem_detector.yml

    - name: Installing Helm Dashboard
      ansible.builtin.include_tasks: 09_install_helm_dashboard.yml
