---
# defaults file for k8s_authentik

# tmpdir
tmpdir: /tmp

nfs_server: nfs.domain.com
kubernetes_ingress_root_domain: domain.com

grafana_admin_user: user
grafana_admin_password: password

grafana_oauth_client_secret: secret
