name: Build and Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  pull-requests: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Deploy Collection to Galaxy
        uses: artis3n/ansible_galaxy_collection@v2
        with:
          api_key: "${{ secrets.GALAXY_TOKEN }}"
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: "COMMIT"
          configuration: .github/changelog-config.json
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          append_body: true
          body: ${{ steps.build_changelog.outputs.changelog }}
          files: |
            hiteshnayak305-homelab*.tar.gz
