---
# handlers file for k8s_init
- name: Restart coredns
  ansible.builtin.command: kubectl rollout restart deployment/coredns -n kube-system
  changed_when: true

- name: Restart kube-proxy
  ansible.builtin.command: kubectl rollout restart daemonset/kube-proxy -n kube-system
  changed_when: true

- name: Recreate control-plane manifests
  become: true
  become_user: root
  ansible.builtin.command: "kubeadm init phase control-plane all --config {{ tmpdir }}/ClusterConfiguration.yml"
  changed_when: true

- name: Recreate etcd manifests
  become: true
  become_user: root
  ansible.builtin.command: "kubeadm init phase etcd local --config {{ tmpdir }}/ClusterConfiguration.yml"
  changed_when: true
